name: Release JAR

on:
  push:
    tags:
      - '**'

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Get tag name
      id: tagname
      run: echo "::set-output name=tagname::${GITHUB_REF#refs/tags/}"

    - name: Extract revision number
      id: revision
      run: echo "::set-output name=revision::$(echo ${{ steps.tagname.outputs.tagname }} | cut -d '.' -f 3)"

    - name: Build with Maven
      run: mvn -B -Drevision=${{ steps.revision.outputs.revision }} clean package --file pom.xml

    - name: Release Assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/*.jar
