name: Release Assets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: mvn clean install

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/ollama4j-web-ui-0.0.1.jar